name: route_log
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  webview_flutter: ^4.13.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  sqflite: ^2.4.2
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
